services:
  app_proxy:
    environment:
      APP_HOST: mieldehabanero-umbrel-swiparr_app_1
      APP_PORT: 4321

  app:
    image: ghcr.io/m3sserstudi0s/swiparr:v0.1.48
    restart: unless-stopped
    volumes:
        - ${APP_DATA_DIR}/data:/app/data:rw
    env_file:
      - ${APP_DATA_DIR}/data/.env
