services:
  app_proxy:
    environment:
      APP_HOST: mieldehabanero-umbrel-maintainerr_app_1
      APP_PORT: 6246

  app:
    image: ghcr.io/maintainerr/maintainerr:2.26.0
    user: 1000:1000
    volumes:
      - ${APP_DATA_DIR}/data:/opt/data:rw
    restart: unless-stopped
    env_file:
      - ${APP_DATA_DIR}/data/.env
